config/routes.rb
Rails.application.routes.draw do
  get '' => 'pages#login'
  namespace :users do
    get 'invites/new'
  end
  resources :user_roles
  devise_for :users, controllers:  {
    sessions: 'users/sessions',
    registrations: 'users/registrations'

  }

 get 'download1' => 'organizations#download1', format: 'docx'
  get 'download2' => 'appraisal_calcs#download2', format: 'docx'
  get 'appraisal_report' => 'appraisal_calcs#appraisal_report', format: 'pdf'
  get 'interim_period/new'
  get 'interim_period/edit'
  get 'interim_period/show'
  get 'interim_period/new'
  get 'interim_period/create'
  #root 'pages#home'
  # config/initializers/high_voltage.rb
HighVoltage.configure do |config|
  config.home_page = 'login'
end

# config/initializers/high_voltage.rb
HighVoltage.configure do |config|
  config.route_drawer = HighVoltage::RouteDrawers::Root
end
  get '/organizations/complete_client_report' => 'organizations#complete_client_report'
  get '/organizations/org_statements/:id' => 'organizations#org_statements'
  get '/appraisal_calcs/pending_appraisal_report' => 'appraisal_calcs#pending_appraisal_report'
  get '/appraisal_calcs/completed_appraisal_report' => 'appraisal_calcs#completed_appraisal_report'
  get '/organizations/pending_client_input_report' => 'organizations#pending_client_input_report'
  patch '/appraisal_calcs/refresh' => 'appraisal_calcs#refresh'
  post '/user/invites/create' => 'users/invites#create'
  resources :appraisal_calcs
  resources :income_statements
  resources :balance_sheets
  resources :organization_stakeholders
  resources :organizations
  resources :stakeholders
  #resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/income_statement.rb
class IncomeStatement < ApplicationRecord
  belongs_to :income_stmt_status
  belongs_to :organization
  before_create :set_status
  before_save :update_status
  after_save :check_completion

  public
    def percent_of_revenue
      self.pretax_profit / self.total_sales
    end
    def calc_owners_perks
      self.owners_travel_exp + self.own_insurance_exp + self.own_veh_exp
    end
    def calc_rent_adjustment
      self.rent - self.organization.futr_rent
    end
    def calc_discretionary_earnings
      self.pretax_profit + self.dep_an_am + self.interest_exp + self.partner_comp +
          self.sal_adj + self.own_retirement + self.calc_owners_perks + self.calc_rent_adjustment + self.non_rec_exp
    end

    def set_status
      self.income_stmt_status_id = 2
    end
  def check_completion
    self.organization.create_appraisal
  end

  def update_status
    self.attributes.each do |obj|
      if obj.nil?
        return
      end
    end
    if self.income_stmt_status_id != 1
      self.income_stmt_status_id = 2
    end

  end

end

app/controllers/income_statements_controller.rb
class IncomeStatementsController < ApplicationController
  before_action :set_income_statement, only: [:show, :edit, :update, :destroy]

  # GET /income_statements
  # GET /income_statements.json
  def index
    if !current_user.is_broker?
      i = Organization.find_by_user_id(current_user.id).id
      @income_statements = IncomeStatement.where(organization_id: i)
    else
    @income_statements = IncomeStatement.all
      end
  end

  # GET /income_statements/1
  # GET /income_statements/1.json
  def show
    if current_user.is_broker? || @income_statement.organization == current_user.get_org
    else
      redirect_to 'client_home'
    end
  end

  # GET /income_statements/new
  def new
    @income_statement = IncomeStatement.new
  end

  # GET /income_statements/1/edit
  def edit
    if current_user.is_broker? || @income_statement.organization == current_user.get_org
    else
      redirect_to 'client_home'
      end
  end

  # POST /income_statements
  # POST /income_statements.json
  def create
    @income_statement = IncomeStatement.new(income_statement_params)    
    @income_statement.organization_id = current_user.get_org.id
    @income_statement.income_stmt_status_id = 3
    respond_to do |format|
      if @income_statement.save
        if current_user.is_broker?
          format.html { redirect_to '/appraiser_home', notice: 'Income Statement was successfully created.' }
          format.json { render :show, status: :created, location: @balance_sheet }
        else
          format.html { redirect_to '/client_home', notice: 'Income statement was successfully created.' }
          format.json { render :show, status: :created, location: @balance_sheet }
        end
      else
        format.html { render :new }
        format.json { render json: @income_statement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /income_statements/1
  # PATCH/PUT /income_statements/1.json
  def update
    if current_user.is_broker? || @income_statement.income_stmt_status_id != 1
    respond_to do |format|
      if @income_statement.update(income_statement_params)
        if current_user.is_broker?
          format.html { redirect_to '/appraiser_home' }
          format.json { render :show, status: :created, location: @balance_sheet }
        else
          format.html { redirect_to '/client_home' }
          format.json { render :show, status: :created, location: @balance_sheet }
        end
      else
        format.html { render :edit }
        format.json { render json: @income_statement.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to '/client_home'
    end

  end

  # DELETE /income_statements/1
  # DELETE /income_statements/1.json
  def destroy
    if current_user.is_broker?
    @income_statement.income_stmt_status_id = 3
    respond_to do |format|
      format.html { redirect_to income_statements_url, notice: 'Income statement was successfully destroyed.' }
      format.json { head :no_content }
    end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income_statement
      @income_statement = IncomeStatement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_statement_params
      params.require(:income_statement).permit(:stmt_year, :total_sales, :pretax_profit, :partner_comp, :dep_an_am,
                                               :interest_exp, :non_rec_exp, :own_veh_exp, :own_insurance_exp,
                                               :income_stmt_status_id, :owners_travel_exp, :sal_adj, :own_retirement,
                                               :cost_of_goods, :organization_id, :payroll, :maintenance, :bad_debt,
                                               :rent, :tax_and_lic, :advertising, :pension_profit_share,
                                               :emp_benefit_cost, :bank_cc_fee, :insurance_cost, :legal_acct_exp,
                                               :outside_exp, :utility, :veh_exp, :est_growth_rate, :stmt_comment,
                                               :int_month, :total_sales_curr, :total_sales_prev, :pretax_profit_curr,
                                               :pretax_profit_prev)
    end
end

app/helpers/income_statements_helper.rb
module IncomeStatementsHelper
end

app/views/income_statements/_form.html.erb
<%= form_with(model: income_statement, local: true) do |form| %>
  <% if income_statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income_statement.errors.count, "error") %> prohibited this income_statement from being saved:</h2>

      <ul>
      <% income_statement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<form>
  <div onload="shows_form_part(1)">

    <div id="form_part1">
      <div class="row">
        <div class="col-md-2">
         <%= form.label :stmt_year, "Statement Year:" %></div>
         <div class="col-sm-2" align="right">
          <%= form.number_field :stmt_year %></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :total_sales, "Total Sales:" %></div>
        <div class="col-sm-2">$
          <%= form.text_field :total_sales %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Total sales for each period. Please enter sales for the past 4 years, the remaining entries will only be for the past 3 years.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :pretax_profit, "Pre-Tax Profit:" %></div>
        <div class="col-sm-2">$
          <%= form.text_field :pretax_profit %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Name of the business.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :partner_comp, "Partner Compensation:" %></div>
        <div class="col-sm-2">$
          <%= form.text_field :partner_comp %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Does not include draws, only compensation listed on the income and expense portion of the tax return or income statement.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :dep_an_am , "Depreciation & Amortization:"%></div>
        <div class="col-sm-2">$
          <%= form.text_field :dep_an_am %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Depreciation is usually on the first page of your tax return, amortization (if any) could be on a schedule later in the return.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :interest_exp , "Interest Expense:"%></div>
        <div class="col-sm-2">$
          <%= form.text_field :interest_exp %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Interest paid on debt. Should not include interest on floor plans or lines of credit used to run the business.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :non_rec_exp , "Non-Typical Expenses:"%></div>
        <div class="col-sm-2">$
          <%= form.text_field :non_rec_exp %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Non-typical expense. Examples include extraordinary legal fees from a lawsuit, accounting fees from an IRS audit, above average write-offs, etc. Should not include cell phone bills, health insurance cost for owners. A negative entry should be made for income such as a gain on the sale of equipment or other income that will not transfer to a buyer. Please explain this entry below.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :own_veh_exp ,"Owner's Vehicle Expense:" %></div>
        <div class="col-sm-2">$
          <%= form.text_field :own_veh_exp %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Auto expense paid by the business but not related to business activities and solely for the Owner's benefit. Note: most businesses need a vehicle, computer and cell phone. Only add what is truly non-essential.">?</a></div>
      </div>

      <div class="row">
        <div class="col-md-2">
          <%= form.label :own_insurance_exp, "Owner's Insurance Expense:" %></div>
        <div class="col-sm-2">$
          <%= form.text_field :own_insurance_exp %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Example; auto insurance on non-essential vehicles, key man insurance for partners, etc.">?</a></div>
      </div>
      <% if current_user.is_broker? %>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :income_stmt_status_id , "Income Statement Status:" %></div>
        <div class="col-sm-2">
          <%= form.collection_select :income_stmt_status_id, IncomeStmtStatus.all, :id, :stmt_status_desc %></div>
      </div>
        <% end %>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :owners_travel_exp , "Owner's Travel Expense:"%></div>
        <div class="col-sm-2">$
          <%= form.text_field :owners_travel_exp %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Travel expense paid by the business but solely for the Owners leisure.">?</a></div>
      </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :sal_adj , "Sales Adjustment:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :sal_adj %></div>
      <div class="col-sm-2">
        <a data-toggle="tooltip" data-placement="Right" title="List the annual salary for family members/partners etc., who were paid by the business but do not actually work in the business. Use a negative entry for a market wage for others who work in the business without pay or to replace more than one owner. Salary.com lists market wage for many different types of positions.">?</a></div>
    </div>

      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-sm-2" align="right">1 of 3</div>
      </div>

    <div align="center">
      <input type="button" onclick="shows_form_part(2)" value="Next">
    </div>

    </div>

    <div id="form_part2" style="display: none;">
      <div class="row">
        <div class="col-md-2">
          <%= form.label :own_retirement , "Owner's Retirement:"%></div>
        <div class="col-sm-2">$
          <%= form.text_field :own_retirement %></div>
        <div class="col-sm-2">
          <a data-toggle="tooltip" data-placement="Right" title="Add the amount of any 401K or similar cost the business paid for the benefit of the owner.">?</a></div>
      </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :cost_of_goods , "Cost Of Goods:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :cost_of_goods %></div>
    </div>


    <div class="row">
      <div class="col-md-2">
        <%= form.label :payroll , "Payroll:"%></div>
      <div class="col-sm-2">
        $ <%= form.text_field :payroll %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :maintenance , "Maintenance:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :maintenance %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :bad_debt , "Bad Debt:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :bad_debt %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :rent , "Rent:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :rent %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :tax_and_lic , "Tax & Licensing:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :tax_and_lic %></div>
      </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :advertising, "Advertising:" %></div>
      <div class="col-sm-2">$
        <%= form.text_field :advertising %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :pension_profit_share , "Pension & Profit Share:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :pension_profit_share %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :emp_benefit_cost, "Employee Benefit & Cost:" %></div>
      <div class="col-sm-2">$
        <%= form.text_field :emp_benefit_cost %></div>
    </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-sm-2" align="right">2 of 3</div>
      </div>
    <div align="center">
        <input type="button" onclick="shows_form_part(1)" value="Back">
        <input type="button" onclick="shows_form_part(3)" value="Next">
    </div>

    </div>

    <div id="form_part3" style="display: none;">
      <div class="row">
        <div class="col-md-2">
          <%= form.label :bank_cc_fee , "Bank & Credit Card Fee:"%></div>
        <div class="col-sm-2">$
          <%= form.text_field :bank_cc_fee %></div>
      </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :insurance_cost , "Insurance Cost:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :insurance_cost %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :legal_acct_exp , "Legal & Accounting Expense:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :legal_acct_exp %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :outside_exp , "Outside Expenses:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :outside_exp %></div>
    </div>


    <div class="row">
      <div class="col-md-2">
        <%= form.label :utility , "Utility Expense:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :utility %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :veh_exp , "Vehicle Expense:"%></div>
      <div class="col-sm-2">$
        <%= form.text_field :veh_exp %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :est_growth_rate , "Estimated Growth Rate:"%></div>
      <div class="col-sm-2" align="right">
        <%= form.text_field :est_growth_rate %></div>
      <div class="col-sm-2">
        <a data-toggle="tooltip" data-placement="Right" title="Enter your anticipated growth (or decline) in total revenue for the next few years. Ex: 3% or -1%, could also be 0.">?</a></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :total_sales_com, "Total Sales Compensation:" %></div>
      <div class="col-sm-2">$
        <%= form.text_field :total_sales_com%></div>
    </div>


    <div class="row">
      <div class="col-md-2">
        <%= form.label :pretax_profit_com, "Pre-Tax Profit Comd:" %></div>
      <div class="col-sm-2">$
        <%= form.text_field :pretax_profit_com %></div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label :stmt_comment , "Statement Comments:"%></div>
      <div class="col-sm-2">
        <%= form.text_area :stmt_comment %></div>
      <div class="col-sm-2">
        <a data-toggle="tooltip" data-placement="Right" title="Please comment as needed including a description of any non-recurring or unusual expense/income.">?</a></div>
    </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-sm-2" align="right">3 of 3</div>
      </div>

      <div onsubmit="return checkForm(this);">
        <div class="row">
          <div align="center">
            <a class="TermCon" href="http://colepartners.net/wp-content/uploads/2013/11/1A-Buyer-NDA.pdf">
              Agreed to Term and Conditions:  </a><input type="checkbox" name="terms">
            <a data-toggle="tooltip" data-placement="Right"
               title="Click on 'Agreed to Term and Conditions:' to view term and conditions document">?</a>
          </div>
        </div>

      </div>

    <div align="center">
      <input type="button" onclick="shows_form_part(2)" value="Back">
      <input type="button" onclick="submit()" value="Save/Submit">
    </div>

    </div>

  </div>
  </form>

<% end %>

app/views/income_statements/edit.html.erb
<nav1>
  <ul>
    <% if current_user.get_org || current_user.is_broker? %>
      <li>  <%= link_to 'Business Information', controller: "organizations", action: "edit", id:@income_statement.organization.id%> </li>
      <% if @income_statement.organization.balance_sheets %>
      <li><%= link_to 'Balance Sheet', controller: "balance_sheets", action: "edit", id: @income_statement.organization.balance_sheets[0] %></li>
    <% else %>
      <li>  <%= link_to 'Balance Sheet', controller: "balance_sheets", action: "new", id: @income_statement.organization.user %> </li>
      <% end %>
      <% if @income_statement.organization.get_stmts != [] %>
        <li> <%= link_to 'Income Statement', controller: "organizations", action: "org_statements", id: @income_statement.organization.id %></li>
      <% else %>
        <li>  <%= link_to 'Income Statement', controller: "income_statements", action: "new", id: @income_statement.organization.user %> </li>
    <% end %>
      <% if current_user.is_broker? && @income_statement.organization.appraisal_calcs[0] %>
        <li>  <%= link_to 'Appraisal', controller: "appraisal_calcs", action: "edit", id: @income_statement.organization.appraisal_calcs[0] %> </li>
      <% end %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      </li>
      <% end %>
  </ul>
</nav1>

<h2>Editing Income Statement</h2>


<%= render 'form', income_statement: @income_statement %>

app/views/income_statements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Income Statements</h1>

<table>
  <thead>
    <tr>
      <th>Stmt year</th>
      <th>Total sales</th>
      <th>Pretax profit</th>
      <th>Partner comp</th>
      <th>Dep an am</th>
      <th>Interest exp</th>
      <th>Non rec exp</th>
      <th>Own veh exp</th>
      <th>Own insurance exp</th>
      <th>Income stmt status</th>
      <th>Owners travel exp</th>
      <th>Sal adj</th>
      <th>Own retirement</th>
      <th>Cost of goods</th>
      <th>Organization</th>
      <th>Payroll</th>
      <th>Maintenance</th>
      <th>Bad debt</th>
      <th>Rent</th>
      <th>Tax and lic</th>
      <th>Advertising</th>
      <th>Pension profit share</th>
      <th>Emp benefit cost</th>
      <th>Bank cc fee</th>
      <th>Insurance cost</th>
      <th>Legal acct exp</th>
      <th>Outside exp</th>
      <th>Utility</th>
      <th>Veh exp</th>
      <th>Est growth rate</th>
      <th>Interim Period Total Sales</th>
      <th>Interim Period Pretax Profit</th>
      <th>Stmt comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @income_statements.each do |income_statement| %>
      <tr>
        <td><%= income_statement.stmt_year %></td>
        <td><%= income_statement.total_sales %></td>
        <td><%= income_statement.pretax_profit %></td>
        <td><%= income_statement.partner_comp %></td>
        <td><%= income_statement.dep_an_am %></td>
        <td><%= income_statement.interest_exp %></td>
        <td><%= income_statement.non_rec_exp %></td>
        <td><%= income_statement.own_veh_exp %></td>
        <td><%= income_statement.own_insurance_exp %></td>
        <td><%= income_statement.income_stmt_status.stmt_status_desc %></td>
        <td><%= income_statement.owners_travel_exp %></td>
        <td><%= income_statement.sal_adj %></td>
        <td><%= income_statement.own_retirement %></td>
        <td><%= income_statement.cost_of_goods %></td>
        <td><%= income_statement.organization.org_name %></td>
        <td><%= income_statement.payroll %></td>
        <td><%= income_statement.maintenance %></td>
        <td><%= income_statement.bad_debt %></td>
        <td><%= income_statement.rent %></td>
        <td><%= income_statement.tax_and_lic %></td>
        <td><%= income_statement.advertising %></td>
        <td><%= income_statement.pension_profit_share %></td>
        <td><%= income_statement.emp_benefit_cost %></td>
        <td><%= income_statement.bank_cc_fee %></td>
        <td><%= income_statement.insurance_cost %></td>
        <td><%= income_statement.legal_acct_exp %></td>
        <td><%= income_statement.outside_exp %></td>
        <td><%= income_statement.utility %></td>
        <td><%= income_statement.veh_exp %></td>
        <td><%= income_statement.est_growth_rate %></td>
        <td><%= income_statement.total_sales%></td>
        <td><%= income_statement.pretax_profit%></td>
        <td><%= income_statement.stmt_comment %></td>
        <td><%= link_to 'View', income_statement %></td>
        <td><%= link_to 'Edit', edit_income_statement_path(income_statement) %></td>
        <td><%= link_to 'Delete', income_statement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income Statement', new_income_statement_path %>

app/views/income_statements/new.html.erb
<nav1>
  <ul>
    <% if current_user.get_org || current_user.is_broker? %>
      <li>  <%= link_to 'Business Information', controller: "organizations", action: "edit", id: current_user.get_org.id%> </li>
      <% if current_user.get_org.balance_sheets %>
        <li><%= link_to 'Balance Sheet', controller: "balance_sheets", action: "edit", id: current_user.get_org.balance_sheets[0] %></li>
      <% else %>
        <li>  <%= link_to 'Balance Sheet', controller: "balance_sheets", action: "new", id: current_user.get_org.user %> </li>
      <% end %>
      <% if current_user.get_org.get_stmts != [] %>
        <li> <%= link_to 'Income Statement', controller: "organizations", action: "org_statements", id: current_user.get_org.id %></li>
      <% else %>
        <li>  <%= link_to 'Income Statement', controller: "income_statements", action: "new", id: current_user.get_org.user %> </li>
      <% end %>
      <% if current_user.is_broker? && current_user.get_org.appraisal_calcs[0] %>
        <li>  <%= link_to 'Appraisal', controller: "appraisal_calcs", action: "edit", id: @income_statement.organization.appraisal_calcs[0] %> </li>
      <% end %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      </li>
    <% end %>
  </ul>
</nav1>
</nav1>
<h3>Enter your Business Income Statement Information</h3>
<%= render 'form', income_statement: @income_statement %>