config/routes.rb
Rails.application.routes.draw do
  get '' => 'pages#login'
  namespace :users do
    get 'invites/new'
  end
  resources :user_roles
  devise_for :users, controllers:  {
    sessions: 'users/sessions',
    registrations: 'users/registrations'

  }

 get 'download1' => 'organizations#download1', format: 'docx'
  get 'download2' => 'appraisal_calcs#download2', format: 'docx'
  get 'appraisal_report' => 'appraisal_calcs#appraisal_report', format: 'pdf'
  get 'interim_period/new'
  get 'interim_period/edit'
  get 'interim_period/show'
  get 'interim_period/new'
  get 'interim_period/create'
  #root 'pages#home'
  # config/initializers/high_voltage.rb
HighVoltage.configure do |config|
  config.home_page = 'login'
end

# config/initializers/high_voltage.rb
HighVoltage.configure do |config|
  config.route_drawer = HighVoltage::RouteDrawers::Root
end
  get '/organizations/complete_client_report' => 'organizations#complete_client_report'
  get '/organizations/org_statements/:id' => 'organizations#org_statements'
  get '/appraisal_calcs/pending_appraisal_report' => 'appraisal_calcs#pending_appraisal_report'
  get '/appraisal_calcs/completed_appraisal_report' => 'appraisal_calcs#completed_appraisal_report'
  get '/organizations/pending_client_input_report' => 'organizations#pending_client_input_report'
  patch '/appraisal_calcs/refresh' => 'appraisal_calcs#refresh'
  post '/user/invites/create' => 'users/invites#create'
  resources :appraisal_calcs
  resources :income_statements
  resources :balance_sheets
  resources :organization_stakeholders
  resources :organizations
  resources :stakeholders
  #resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/reports/complete_client_report.erb
<table>
  <thead>
  <tr>
    <th>Org name</th>
    <th>Org address</th>
    <th>Org city</th>
    <th>State</th>
    <th>Org zip</th>
    <th>Org website</th>
    <th>Full emp</th>
    <th>Part emp</th>
    <th>Founding year</th>
    <th>Ownership type</th>
    <th>Prim naics</th>
    <th>Sec naics</th>
    <th>Brief desc of services</th>
    <th>Real estate type</th>
    <th>Real estate included</th>
    <th>Futr rent</th>
    <th>Lease expir date</th>
    <th>Extend date</th>
    <th>Hist earning ranking</th>
    <th>Finance rec ranking</th>
    <th>Depth of management ranking</th>
    <th>Loc and fac ranking</th>
    <th>Competition ranking</th>
    <th>Diversification ranking</th>
    <th>Equipment sys ranking</th>
    <th>Employee skill turnover ranking</th>
    <th>Desirability ranking</th>
    <th>Hist org performance ranking</th>
    <th>Org comment</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @organizations.each do |organization| %>
    <tr>
      <td><%= organization.org_name %></td>
      <td><%= organization.org_address %></td>
      <td><%= organization.org_city %></td>
      <td><%= organization.state %></td>
      <td><%= organization.org_zip %></td>
      <td><%= organization.org_website %></td>
      <td><%= organization.full_emp %></td>
      <td><%= organization.part_emp %></td>
      <td><%= organization.founding_year %></td>
      <td><%= organization.ownership_type %></td>
      <td><%= organization.prim_naics %></td>
      <td><%= organization.sec_naics %></td>
      <td><%= organization.brief_desc_of_services %></td>
      <td><%= organization.real_estate_type %></td>
      <td><%= organization.real_estate_included %></td>
      <td><%= organization.futr_rent %></td>
      <td><%= organization.lease_expir_date %></td>
      <td><%= organization.extend_date %></td>
      <td><%= organization.hist_earning_ranking %></td>
      <td><%= organization.finance_rec_ranking %></td>
      <td><%= organization.depth_of_management_ranking %></td>
      <td><%= organization.loc_and_fac_ranking %></td>
      <td><%= organization.competition_ranking %></td>
      <td><%= organization.diversification_ranking %></td>
      <td><%= organization.equipment_sys_ranking %></td>
      <td><%= organization.employee_skill_turnover_ranking %></td>
      <td><%= organization.desirability_ranking %></td>
      <td><%= organization.hist_org_performance_ranking %></td>
      <td><%= organization.org_comment %></td>
      <td><%= link_to 'View', organization %></td>
      <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
      <td><%= link_to 'Delete', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>